### ISSUE TITLE
Using gulp to uglify, lint and test

### ISSUE THREAD

**Issue by softwarespot** [ryanmorr/is-style-supported#6]
Have you thought about using gulp to minify, lint and test this excellent module? Let me know and I can send a PR with a custom gulp script.

**Comment by ryanmorr** [comment]
I haven't yet decided, but it's something I would like to do on my own accord (I'm a little particular on how I set up task runners). I appreciate the offer and the other fixes/suggestions.

**Comment by softwarespot** [comment]
No problem whatsoever =)
